Event / Store API 기능.. 개발
Bakery-EFUB/Bakery-Back pull request #11
Opened 2022-07-17 06:59 UTC by gimkuku

앞으로 해야하는 일 
[] 시연이 코드와 합쳐서 member 넣고 데이터 저장하기
[] store 쿼리로 필터링하는 것
[] 이미지 presigned URL 사용해서 S3에 올리기 (이것도 시연이 코드 합치고 넣어야 됨.. ) 

--- 

오늘 내로 풀리퀘 확인하고 머지하면 바로 수정하겠삼!

2022-07-19 08:11 UTC, siyeonkm commented on src/main/java/bakery/caker/controller/EventController.java
> +    public EventController(EventService eventService) {
lombok 어노테이션을 쓰면 이거 굳이 이렇게 손수 생성자 주입 안해줘도돼요!

내 코드 보면 볼 수 있는데, 
1) class에 @RequiredArgsConstructor를 달아주고
2) EventService를 private final로 선언해주기!!

RequiredArgsConstructor가 final / notnull로 선언된 값들만 파라미터로 받는 생성자를 자동으로 만들어주는 어노테이션이에용

이거 쓰면 빠르게 주입가능합니당!

2022-07-19 08:15 UTC, siyeonkm commented on src/main/java/bakery/caker/controller/EventController.java
> +@Controller
큰 차이는 없지만 주로 이거보다는 @RestController를 달아서 사용합니다!

@Controller는 주로 view를 반환할때 사용해요
1) 이거 달은 controller에서 getmapping하고 
2) return "home"이렇게 해놓은다음에,
3) home.html을 resources/templates에 만들어놓으면 home.html 뷰를 반환하는식!

@RestController가 주로 data를 반환해야할때 사용해요 json형 데이터

어노테이션에 따라 오류가 좀 나는경우도 있으니까 @RestController로 바꾸면 좋을듯!

2022-07-19 08:16 UTC, gimkuku commented on src/main/java/bakery/caker/controller/EventController.java
> +@Controller
그렇군요!!!!!!1 감사합니더.,.

2022-07-19 08:16 UTC, siyeonkm commented on src/main/java/bakery/caker/controller/EventController.java
> +    ResponseEntity<?> getEventList(@PathVariable("store_id") Long store_id) {
Spring에서는 변수값 주로 카멜체로 써가지구
Long store_id → storeId로 바꿔주면 굿

2022-07-19 08:16 UTC, gimkuku commented on src/main/java/bakery/caker/controller/EventController.java
> +    public EventController(EventService eventService) {
오홍! 아 어쩐지 private final 이 있어서 그랬군용,,

2022-07-19 08:17 UTC, siyeonkm commented on src/main/java/bakery/caker/controller/EventController.java
> +    ResponseEntity<?> delete(@PathVariable("store_id") Long store_id,
여기두 카멜체로!

2022-07-19 08:21 UTC, siyeonkm commented on src/main/java/bakery/caker/controller/StoreController.java
> +    private MemberRepository memberRepository;
이왕이면 controller에서는 Service만 액세스하는게 좋을거같아요!

repository가 필요한 작업은 service단에서만!

2022-07-19 08:22 UTC, siyeonkm commented on src/main/java/bakery/caker/controller/StoreController.java
> +    private MemberRepository memberRepository;
앗 찾아보니 StoreController에서 memberRepository쓰는 부분이 없네! 지워주면 될듯 :D

2022-07-19 08:22 UTC, kji-dec commented on src/main/java/bakery/caker/controller/StoreController.java
> +    private MemberRepository memberRepository;
뭐야 리뷰하러 들어왔는데 왤케 빨라여,,,

2022-07-19 08:22 UTC, siyeonkm commented on src/main/java/bakery/caker/controller/StoreController.java
> +@Controller
여기두 rest로!

2022-07-19 08:23 UTC, siyeonkm commented on src/main/java/bakery/caker/controller/StoreController.java
> +@Controller
아 그리고 지금 보면 모든 rest api 요청에 "/stores"가 들어갔잖아,
그러면 여기 class위에 @RequestMapping("/stores") 이렇게하면
기본으로 모든 url앞에 저게 붙어! 그러면 좀더 깔끔해진답니다

2022-07-19 08:27 UTC, gimkuku commented on src/main/java/bakery/caker/controller/EventController.java
> +    ResponseEntity<?> getEventList(@PathVariable("store_id") Long store_id) {
헛넵.. !

2022-07-19 08:27 UTC, gimkuku commented on src/main/java/bakery/caker/controller/StoreController.java
> +    private MemberRepository memberRepository;
헉 글쿤용,,! 저는 필요한거 다 갖다써서 8ㅅ8

2022-07-19 08:28 UTC, siyeonkm commented on src/main/java/bakery/caker/domain/Event.java
> +@EntityListeners(AuditingEntityListener.class) /* JPA에게 해당 Entity는 Auditiong 기능을 사용함을 알립니다. */
AuditingEntityListener는 jpa에서 특정 조건을 충족했을때 값을 자동으로 넣어줄 수 있게 하겠다는 어노테이션이야!

그래서 주로, 생성일자나 수정일자같은거 자동으로 표기하고싶을때 붙여서, 여기서는 필요없을거같아요

2022-07-19 08:31 UTC, siyeonkm commented on src/main/java/bakery/caker/domain/Store.java
> +    private LocalDateTime createdDate;
우리 db보면 여러 테이블에 createdDate가 있는데,
이렇게 중복으로 생성일자가 여러곳에 들어가는 경우에는

1)baseEntity라는 추상화 클래스 엔티티를 따로 만들고,
2) 거기에 createdDate 변수를 만들구
3) 걔를 extends로 createdDate가 들어가는 테이블에 붙여주는 식으로 코딩을 많이해요!

이거는 내가 카톡에 참고할만한 샘플코드 보내줄게

2022-07-19 08:35 UTC, siyeonkm commented on src/main/java/bakery/caker/domain/Store.java
> +    @JoinColumn(name = "member_id", nullable = false)
nullable = false로도 적어줄 수 있는데,
아니면 그냥 따로 어노테이션을 @NotNull이렇게도 적어줄 수 있음!

큰 차이는 없는데, nullable = false는 데이터베이스에 notnull제약조건만 걸어주고, 유효성 검사는 안해줘서 null값을 넣으려고 시도하다가 오류가 나고,
@NotNull은 null값을 넣는 행동을 하려고 하면 유효성 검증 과정에서 오류를 발생시켜줌 미리!

2022-07-19 08:36 UTC, siyeonkm commented on src/main/java/bakery/caker/domain/Store.java
> +    public Store(Long id, Member owner, String name, String mainImg, String readme, String address, String kakaoUrl, String instagram, Boolean certifyFlag,String openTime, String phoneNumber, LocalDa
id는 auto increment로 자동으로 생기니까 store 엔티티 생성할때 Long id값을 안넘겨도됨! 그래서 빼는게 좋아용
그리고 나중에 baseEntity 사용해서 값 생성시 자동으로 createdDate 값 들어가도록 수정하게되면 얘도 builder에서 빼도됨. 자동으로 들어감!

2022-07-19 08:37 UTC, siyeonkm commented on src/main/java/bakery/caker/dto/StoreRequestDTO.java
> +    private LocalDateTime createdDate;
아까 말했듯이, 값 넣을때 자동으로 넣어줄 수 있어서 프론트측에서 요청 안해도될듯

2022-07-19 08:38 UTC, siyeonkm commented on src/main/java/bakery/caker/repository/EventRepository.java
> +    List<Event> findAllEventByStoreId(Long store_id);
카멜체!

2022-07-19 08:51 UTC, kji-dec commented on src/main/java/bakery/caker/service/EventService.java
> +        if( owner_id == store.get().getOwner().getMemberId()){
Long 타입 숫자가 127보다 커지면 == 로 비교가 안되니까 .equals 쓰는 게 더 좋을 것 같습니다!

ownerId.equals(~) 이런식으루!

2022-07-19 09:04 UTC, siyeonkm commented on src/main/java/bakery/caker/service/StoreService.java
> +        List<Store> StoreList = storeRepository.findAll();
Store Repository에다가
`List<Store> findStoresByOwner_DeleteFlag(Boolean deleteFlag);`
이런식으로도 코드 짤 수 있는데, 

이거로 storeList받아오면:
`storeRepository.findStoresByOwner_DeleteFlag(false);`

밑에 주인장 deleteflag가 false가 아닌 애들 찾기위한 if문은 없앨 수 있을거같아!

2022-07-19 09:13 UTC, siyeonkm commented on src/main/java/bakery/caker/service/EventService.java
> +        if( owner_id == store.get().getOwner().getMemberId()){
오오 생각못했네 굿굿

2022-07-19 14:51 UTC, siyeonkm commented on src/main/java/bakery/caker/repository/StoreRepository.java
> +    List<Store> findAll_DeleteFlag(Boolean deleteFlag);
이거는 올바른 sql이 아니에요~

findStoresByOwner_DeleteFlag(Boolean deleteFlag); 여야합니다.

가게들을 owner 애트리뷰트로 판별해서 가져오는데, 그 owner가 deleteflag가 false여야 한다는 뜻임!
→ Member entity에 있는 deleteflag까지 여기서 sql문으로 원큐에 확인하는 식임

2022-07-19 15:07 UTC, siyeonkm requested changes
내가 말을 너무 완곡하게 썼던듯 ㅋㅋㅋ
1. RequiredArgsConstructor 식으로 의존성 주입하는경우가 더 많으니까 이거로 고쳐줘요
2. 지인이 코드 머지한거 끌고와서 createdDate 다 삭제하고 extends BaseTimeEntity로 바꿔줘용
3. 2번을 하고나면, RequestDTO들에서도 createdDate 다 빼줘야함!
4. controller에 있는 함수들에서 앞에 get/update/delete/patch 붙인것들 다 떼버리기! 쟤네 4개는 함수이름에 넣지말아줘요

2022-07-20 00:10 UTC, gimkuku reviewed
1. 파일 명에 .이 있을 경우 확장자가 잘못 저장되는 에러 발견 
``` indexOf -> lastIndexOf 로 수정```
2. 검색쿼리에서 StoreResponseDTO 수정 안해둔 것 발견,, Store 로 바꿈

2022-07-20 03:40 UTC, siyeonkm commented on src/main/java/bakery/caker/service/StoreService.java
> +        List<Store> storeResponseDTOList = storeRepository.findByNameContaining(q);
findAllByNameContaining을 findByNameContaining으로 바꾸면,
findAll은 모두 찾는건데, find는 하나만 찾는거라 오류가 날거같아요! 내가 일단 한번 돌려보고 오류나면, 알려줄게

List<StoreResponseDTO>를 List<Store> 로 바꾼거는 잘했어요

2022-07-20 07:15 UTC, siyeonkm commented on src/main/java/bakery/caker/service/StoreService.java
> +        List<Store> storeResponseDTOList = storeRepository.findByNameContaining(q);
오 잘되네요 내가 착각했나봐 굿굿

2022-07-20 07:16 UTC, siyeonkm approved these changes

2022-07-20 09:27 UTC, merged